### ISSUE TITLE
Error after latest commit

### ISSUE THREAD

**Issue by payal97** [systers/portal#164]
python manage.py runserver gives the following error after the latest commit ['Squash users app migrations and update deps'](https://github.com/systers/portal/commit/eeb03a500c8315fcf16af9268887468782a0aa57)

`payal@Payal:~/projects/systers_portal/portal/systers_portal|develop⇒  python manage.py runserver 
Performing system checks...

System check identified no issues (0 silenced).
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f0e1d1d9598>
Traceback (most recent call last):
  File "/home/payal/projects/systers_portal/portal/venv/lib/python3.4/site-packages/django/utils/autoreload.py", line 222, in wrapper
    fn(*args, **kwargs)
  File "/home/payal/projects/systers_portal/portal/venv/lib/python3.4/site-packages/django/core/management/commands/runserver.py", line 107, in inner_run
    self.check_migrations()
  File "/home/payal/projects/systers_portal/portal/venv/lib/python3.4/site-packages/django/core/management/commands/runserver.py", line 159, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "/home/payal/projects/systers_portal/portal/venv/lib/python3.4/site-packages/django/db/migrations/executor.py", line 17, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/home/payal/projects/systers_portal/portal/venv/lib/python3.4/site-packages/django/db/migrations/loader.py", line 48, in __init__
    self.build_graph()
  File "/home/payal/projects/systers_portal/portal/venv/lib/python3.4/site-packages/django/db/migrations/loader.py", line 245, in build_graph
    self.graph.add_dependency(migration, key, parent)
  File "/home/payal/projects/systers_portal/portal/venv/lib/python3.4/site-packages/django/db/migrations/graph.py", line 46, in add_dependency
    "Migration %s dependencies reference nonexistent parent node %r" % (migration, parent)
KeyError: "Migration meetup.0001_initial dependencies reference nonexistent parent node ('users', '0001_squashed_0003_auto_20160207_1550')"
`

**Comment by payal97** [comment]
@ana-balica could you look into this?
The file '0001_squashed_0003_auto_20160207_1550.py' exists in users/migrations. I'm not able to figure out why this error is coming up. 'python manage.py migrate' is giving the same error.

**Comment by smarshy** [comment]
@payal97 I ran into the same error just a few minutes back. Maybe you could try recreating the database, making migrations and migrating. It worked in my case. Hope this helps :)

**Comment by payal97** [comment]
@smarshy that worked for me. Thanks!
